name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Install and run project
      run: |
        make install
        make run &  # Run the server in the background
        sleep 30  # Wait for the server to start

    - name: Check server response
      run: |
        for i in {1..10}; do  # Try up to 10 times
          if curl -f http://localhost:3000; then
            echo "Server is up!"
            exit 0
          fi
          echo "Waiting for server to start..."
          sleep 5  # Wait before trying again
        done
        exit 1  # Fail if the server did not start
